### PR TITLE
Changes to allow initializing the component programmatically

### PR DESCRIPTION
**Pull request by marnore**
Added initialization of default values, thus SuperSaiyanScrollView can be initialized pgrammatically. Added dark overlay drawable to fit Holo Dark theme

### CODE REVIEW

**Comment by nolanlawson** [comment]
Awesome, thanks! I will get this merged soon and then push out a new release. Also thinking of switching to Gradle.

**Comment by nolanlawson** [comment]
Sorry, been swamped with work, but this will definitely get done this weekend.

**Comment by marnore** [comment]
No problem. I am using this in my project and the fast scrolling really looks cool there! Though I was also thinking of adding some code to measure the sections text automatically so it would scale to any input. It would also be nice to have faster startup time but I guess there isn't much to do about that :)

**Comment by nolanlawson** [comment]
Startup is pretty good on my end, but I'm not using a lot of data.  It'd be nice to profile it so I know what's taking so long!

As for this commit, it's been merged as b24edd9ac45ada174768d4d59630a6fbcc57183c.  Thanks a ton!

**Pull request closed without merging**
